In [116]:
import pandas as pd
import numpy as np
import spacy
import re

In [117]:
def load_data_fn() -> pd.DataFrame:
  """
  Rjesava se praznina koje dobijemo kod obicnog pd.read_csv

  PARAMETERS:
    data (pd.Dataframe): pandas dataframe kad ucitas sa pd.read_csv
  """
  with open("/content/friends.train.scene_delim.conll") as d:
    result = []
    for item in d:
      tmp = re.sub("\s", "|", item)
      tmp2 = tmp.split("|")
      lst = []
      for el in tmp2:
        if el != "":
          lst.append(el)
      result.append(lst)
    df = pd.DataFrame(result, columns=["Document ID","Scene ID","Token ID","Word form","Part-of-speech tag","Constituency tag","Lemma","Frameset ID", "Word sense", "Speaker", "Named entity tag", "Entity ID"])
    # df.drop(df.tail(1).index,inplace=True)
    # df.drop(df.head(1).index,inplace=True)
    # df.dropna(inplace=True)
    return df

data = load_data_fn()

In [118]:
data2 = data[:973] # ovdje je prvi #end pa 
data2

         Document ID  Scene ID  ... Named entity tag Entity ID
0             #begin  document  ...             None      None
1    /friends-s01e01         0  ...                *         -
2    /friends-s01e01         0  ...                *         -
3    /friends-s01e01         0  ...                *         -
4    /friends-s01e01         0  ...                *         -
..               ...       ...  ...              ...       ...
968  /friends-s01e01         0  ...                *         -
969  /friends-s01e01         0  ...                *         -
970  /friends-s01e01         0  ...                *         -
971             None      None  ...             None      None
972             #end  document  ...             None      None

[973 rows x 12 columns]

In [122]:
data2.drop(data2.head(1).index,inplace=True)
data2.drop(data2.tail(1).index,inplace=True)
data2

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

         Document ID Scene ID  ... Named entity tag Entity ID
1    /friends-s01e01        0  ...                *         -
2    /friends-s01e01        0  ...                *         -
3    /friends-s01e01        0  ...                *         -
4    /friends-s01e01        0  ...                *         -
5    /friends-s01e01        0  ...                *         -
..               ...      ...  ...              ...       ...
967  /friends-s01e01        0  ...                *         -
968  /friends-s01e01        0  ...                *         -
969  /friends-s01e01        0  ...                *         -
970  /friends-s01e01        0  ...                *         -
971             None     None  ...             None      None

[971 rows x 12 columns]

In [127]:
data2[["Scene ID", "Token ID"]] = data2[["Scene ID", "Token ID"]].apply(pd.to_numeric).astype("Int64")

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:3069: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [128]:
data2["Token ID"]

1         0
2         1
3         2
4         3
5         4
       ...
967       9
968      10
969      11
970      12
971    <NA>
Name: Token ID, Length: 971, dtype: Int64

In [129]:
data2.dtypes

Document ID           object
Scene ID               Int64
Token ID               Int64
Word form             object
Part-of-speech tag    object
Constituency tag      object
Lemma                 object
Frameset ID           object
Word sense            object
Speaker               object
Named entity tag      object
Entity ID             object
dtype: object

In [130]:
data2 = pd.concat([data.head(1), data2, data.tail(1)])

In [131]:
data2

          Document ID  Scene ID  ... Named entity tag Entity ID
0              #begin  document  ...             None      None
1     /friends-s01e01         0  ...                *         -
2     /friends-s01e01         0  ...                *         -
3     /friends-s01e01         0  ...                *         -
4     /friends-s01e01         0  ...                *         -
...               ...       ...  ...              ...       ...
968   /friends-s01e01         0  ...                *         -
969   /friends-s01e01         0  ...                *         -
970   /friends-s01e01         0  ...                *         -
971              None      <NA>  ...             None      None
3717             #end  document  ...             None      None

[973 rows x 12 columns]

In [132]:
data2.to_csv('file.v4_gold_conll', sep="\t", index=False, header=None)